name: screenshot_callback_pro
description: screenshot_callback_pro,No permission required, just call back directly.This library is very user-friendly.
version: 0.0.5
homepage: https://github.com/LiuDongCai/screenshot_callback_pro

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pigeon: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.liudongcai.screenshot_callback_pro
        pluginClass: ScreenshotCallbackPlugin
      ios:
        pluginClass: ScreenshotCallbackPlugin